#include <nui/frontend/elements/a.hpp>
#include <nui/frontend/elements/abbr.hpp>
#include <nui/frontend/elements/address.hpp>
#include <nui/frontend/elements/area.hpp>
#include <nui/frontend/elements/article.hpp>
#include <nui/frontend/elements/aside.hpp>
#include <nui/frontend/elements/audio.hpp>
#include <nui/frontend/elements/b.hpp>
#include <nui/frontend/elements/base.hpp>
#include <nui/frontend/elements/bdi.hpp>
#include <nui/frontend/elements/bdo.hpp>
#include <nui/frontend/elements/blockquote.hpp>
#include <nui/frontend/elements/body.hpp>
#include <nui/frontend/elements/br.hpp>
#include <nui/frontend/elements/button.hpp>
#include <nui/frontend/elements/canvas.hpp>
#include <nui/frontend/elements/caption.hpp>
#include <nui/frontend/elements/cite.hpp>
#include <nui/frontend/elements/code.hpp>
#include <nui/frontend/elements/comment.hpp>
#include <nui/frontend/elements/data.hpp>
#include <nui/frontend/elements/datalist.hpp>
#include <nui/frontend/elements/dd.hpp>
#include <nui/frontend/elements/del.hpp>
#include <nui/frontend/elements/details.hpp>
#include <nui/frontend/elements/dfn.hpp>
#include <nui/frontend/elements/dialog.hpp>
#include <nui/frontend/elements/div.hpp>
#include <nui/frontend/elements/dl.hpp>
#include <nui/frontend/elements/dt.hpp>
#include <nui/frontend/elements/em.hpp>
#include <nui/frontend/elements/embed.hpp>
#include <nui/frontend/elements/fieldset.hpp>
#include <nui/frontend/elements/figcaption.hpp>
#include <nui/frontend/elements/figure.hpp>
#include <nui/frontend/elements/footer.hpp>
#include <nui/frontend/elements/form.hpp>
#include <nui/frontend/elements/fragment.hpp>
#include <nui/frontend/elements/head.hpp>
#include <nui/frontend/elements/header.hpp>
#include <nui/frontend/elements/heading.hpp>
#include <nui/frontend/elements/hr.hpp>
#include <nui/frontend/elements/i.hpp>
#include <nui/frontend/elements/iframe.hpp>
#include <nui/frontend/elements/img.hpp>
#include <nui/frontend/elements/input.hpp>
#include <nui/frontend/elements/ins.hpp>
#include <nui/frontend/elements/kbd.hpp>
#include <nui/frontend/elements/label.hpp>
#include <nui/frontend/elements/legend.hpp>
#include <nui/frontend/elements/li.hpp>
#include <nui/frontend/elements/link.hpp>
#include <nui/frontend/elements/main.hpp>
#include <nui/frontend/elements/map.hpp>
#include <nui/frontend/elements/mark.hpp>
#include <nui/frontend/elements/meta.hpp>
#include <nui/frontend/elements/meter.hpp>
#include <nui/frontend/elements/nav.hpp>
#include <nui/frontend/elements/nil.hpp>
#include <nui/frontend/elements/noscript.hpp>
#include <nui/frontend/elements/object.hpp>
#include <nui/frontend/elements/ol.hpp>
#include <nui/frontend/elements/optgroup.hpp>
#include <nui/frontend/elements/option.hpp>
#include <nui/frontend/elements/output.hpp>
#include <nui/frontend/elements/p.hpp>
#include <nui/frontend/elements/param.hpp>
#include <nui/frontend/elements/picture.hpp>
#include <nui/frontend/elements/pre.hpp>
#include <nui/frontend/elements/progress.hpp>
#include <nui/frontend/elements/q.hpp>
#include <nui/frontend/elements/rp.hpp>
#include <nui/frontend/elements/rt.hpp>
#include <nui/frontend/elements/ruby.hpp>
#include <nui/frontend/elements/s.hpp>
#include <nui/frontend/elements/samp.hpp>
#include <nui/frontend/elements/script.hpp>
#include <nui/frontend/elements/section.hpp>
#include <nui/frontend/elements/select.hpp>
#include <nui/frontend/elements/small.hpp>
#include <nui/frontend/elements/source.hpp>
#include <nui/frontend/elements/span.hpp>
#include <nui/frontend/elements/strong.hpp>
#include <nui/frontend/elements/sub.hpp>
#include <nui/frontend/elements/summary.hpp>
#include <nui/frontend/elements/sup.hpp>
#include <nui/frontend/elements/switch.hpp>
#include <nui/frontend/elements/table.hpp>
#include <nui/frontend/elements/tbody.hpp>
#include <nui/frontend/elements/td.hpp>
#include <nui/frontend/elements/template.hpp>
#include <nui/frontend/elements/text.hpp>
#include <nui/frontend/elements/textarea.hpp>
#include <nui/frontend/elements/tfoot.hpp>
#include <nui/frontend/elements/th.hpp>
#include <nui/frontend/elements/thead.hpp>
#include <nui/frontend/elements/time.hpp>
#include <nui/frontend/elements/title.hpp>
#include <nui/frontend/elements/tr.hpp>
#include <nui/frontend/elements/track.hpp>
#include <nui/frontend/elements/u.hpp>
#include <nui/frontend/elements/ul.hpp>
#include <nui/frontend/elements/var.hpp>
#include <nui/frontend/elements/video.hpp>
#include <nui/frontend/elements/wbr.hpp>