#pragma once

#include <nui/frontend/elements/svg/a.hpp>
#include <nui/frontend/elements/svg/animate.hpp>
#include <nui/frontend/elements/svg/animate_motion.hpp>
#include <nui/frontend/elements/svg/animate_transform.hpp>
#include <nui/frontend/elements/svg/circle.hpp>
#include <nui/frontend/elements/svg/clipPath.hpp>
#include <nui/frontend/elements/svg/defs.hpp>
#include <nui/frontend/elements/svg/desc.hpp>
#include <nui/frontend/elements/svg/ellipse.hpp>
#include <nui/frontend/elements/svg/fe_blend.hpp>
#include <nui/frontend/elements/svg/fe_color_matrix.hpp>
#include <nui/frontend/elements/svg/fe_component_transfer.hpp>
#include <nui/frontend/elements/svg/fe_composite.hpp>
#include <nui/frontend/elements/svg/fe_convolve_matrix.hpp>
#include <nui/frontend/elements/svg/fe_diffuse_lighting.hpp>
#include <nui/frontend/elements/svg/fe_displacement_map.hpp>
#include <nui/frontend/elements/svg/fe_distant_light.hpp>
#include <nui/frontend/elements/svg/fe_drop_shadow.hpp>
#include <nui/frontend/elements/svg/fe_flood.hpp>
#include <nui/frontend/elements/svg/fe_func.hpp>
#include <nui/frontend/elements/svg/fe_func_a.hpp>
#include <nui/frontend/elements/svg/fe_func_b.hpp>
#include <nui/frontend/elements/svg/fe_func_g.hpp>
#include <nui/frontend/elements/svg/fe_func_r.hpp>
#include <nui/frontend/elements/svg/fe_gaussian_blur.hpp>
#include <nui/frontend/elements/svg/fe_image.hpp>
#include <nui/frontend/elements/svg/fe_merge.hpp>
#include <nui/frontend/elements/svg/fe_merge_node.hpp>
#include <nui/frontend/elements/svg/fe_morphology.hpp>
#include <nui/frontend/elements/svg/fe_offset.hpp>
#include <nui/frontend/elements/svg/fe_point_light.hpp>
#include <nui/frontend/elements/svg/fe_specular_lighting.hpp>
#include <nui/frontend/elements/svg/fe_spot_light.hpp>
#include <nui/frontend/elements/svg/fe_tile.hpp>
#include <nui/frontend/elements/svg/fe_turbulence.hpp>
#include <nui/frontend/elements/svg/filter.hpp>
#include <nui/frontend/elements/svg/foreign_object.hpp>
#include <nui/frontend/elements/svg/g.hpp>
#include <nui/frontend/elements/svg/hatch.hpp>
#include <nui/frontend/elements/svg/hatchpath.hpp>
#include <nui/frontend/elements/svg/image.hpp>
#include <nui/frontend/elements/svg/line.hpp>
#include <nui/frontend/elements/svg/linear_gradient.hpp>
#include <nui/frontend/elements/svg/marker.hpp>
#include <nui/frontend/elements/svg/mask.hpp>
#include <nui/frontend/elements/svg/metadata.hpp>
#include <nui/frontend/elements/svg/mpath.hpp>
#include <nui/frontend/elements/svg/path.hpp>
#include <nui/frontend/elements/svg/pattern.hpp>
#include <nui/frontend/elements/svg/polygon.hpp>
#include <nui/frontend/elements/svg/polyline.hpp>
#include <nui/frontend/elements/svg/radial_gradient.hpp>
#include <nui/frontend/elements/svg/rect.hpp>
#include <nui/frontend/elements/svg/script.hpp>
#include <nui/frontend/elements/svg/set.hpp>
#include <nui/frontend/elements/svg/stop.hpp>
#include <nui/frontend/elements/svg/style.hpp>
#include <nui/frontend/elements/svg/svg.hpp>
#include <nui/frontend/elements/svg/switch.hpp>
#include <nui/frontend/elements/svg/symbol.hpp>
#include <nui/frontend/elements/svg/text.hpp>
#include <nui/frontend/elements/svg/textPath.hpp>
#include <nui/frontend/elements/svg/title.hpp>
#include <nui/frontend/elements/svg/tspan.hpp>
#include <nui/frontend/elements/svg/use.hpp>
#include <nui/frontend/elements/svg/view.hpp>
