#pragma once

#include <nui/frontend/attributes/svg/accent_height.hpp>
#include <nui/frontend/attributes/svg/accumulate.hpp>
#include <nui/frontend/attributes/svg/additive.hpp>
#include <nui/frontend/attributes/svg/alignment_baseline.hpp>
#include <nui/frontend/attributes/svg/alphabetic.hpp>
#include <nui/frontend/attributes/svg/amplitude.hpp>
#include <nui/frontend/attributes/svg/arabic_form.hpp>
#include <nui/frontend/attributes/svg/ascent.hpp>
#include <nui/frontend/attributes/svg/attribute_name.hpp>
#include <nui/frontend/attributes/svg/attribute_type.hpp>
#include <nui/frontend/attributes/svg/azimuth.hpp>
#include <nui/frontend/attributes/svg/baseline_shift.hpp>
#include <nui/frontend/attributes/svg/base_frequency.hpp>
#include <nui/frontend/attributes/svg/base_profile.hpp>
#include <nui/frontend/attributes/svg/bbox.hpp>
#include <nui/frontend/attributes/svg/begin.hpp>
#include <nui/frontend/attributes/svg/bias.hpp>
#include <nui/frontend/attributes/svg/by.hpp>
#include <nui/frontend/attributes/svg/calc_mode.hpp>
#include <nui/frontend/attributes/svg/cap_height.hpp>
#include <nui/frontend/attributes/svg/class.hpp>
#include <nui/frontend/attributes/svg/clip.hpp>
#include <nui/frontend/attributes/svg/clip_path.hpp>
#include <nui/frontend/attributes/svg/clip_path_units.hpp>
#include <nui/frontend/attributes/svg/clip_rule.hpp>
#include <nui/frontend/attributes/svg/color.hpp>
#include <nui/frontend/attributes/svg/color_interpolation.hpp>
#include <nui/frontend/attributes/svg/color_interpolation_filters.hpp>
#include <nui/frontend/attributes/svg/color_profile.hpp>
#include <nui/frontend/attributes/svg/color_rendering.hpp>
#include <nui/frontend/attributes/svg/content_script_type.hpp>
#include <nui/frontend/attributes/svg/content_style_type.hpp>
#include <nui/frontend/attributes/svg/crossorigin.hpp>
#include <nui/frontend/attributes/svg/cursor.hpp>
#include <nui/frontend/attributes/svg/cx.hpp>
#include <nui/frontend/attributes/svg/cy.hpp>
#include <nui/frontend/attributes/svg/d.hpp>
#include <nui/frontend/attributes/svg/descelerate.hpp>
#include <nui/frontend/attributes/svg/descent.hpp>
#include <nui/frontend/attributes/svg/diffuse_constant.hpp>
#include <nui/frontend/attributes/svg/direction.hpp>
#include <nui/frontend/attributes/svg/display.hpp>
#include <nui/frontend/attributes/svg/divisor.hpp>
#include <nui/frontend/attributes/svg/dominant_baseline.hpp>
#include <nui/frontend/attributes/svg/dur.hpp>
#include <nui/frontend/attributes/svg/dx.hpp>
#include <nui/frontend/attributes/svg/dy.hpp>
#include <nui/frontend/attributes/svg/edge_mode.hpp>
#include <nui/frontend/attributes/svg/elevation.hpp>
#include <nui/frontend/attributes/svg/enable_background.hpp>
#include <nui/frontend/attributes/svg/end.hpp>
#include <nui/frontend/attributes/svg/exponent.hpp>
#include <nui/frontend/attributes/svg/fill.hpp>
#include <nui/frontend/attributes/svg/fill_opacity.hpp>
#include <nui/frontend/attributes/svg/fill_rule.hpp>
#include <nui/frontend/attributes/svg/filter.hpp>
#include <nui/frontend/attributes/svg/filter_res.hpp>
#include <nui/frontend/attributes/svg/filter_units.hpp>
#include <nui/frontend/attributes/svg/flood_color.hpp>
#include <nui/frontend/attributes/svg/font_family.hpp>
#include <nui/frontend/attributes/svg/font_size.hpp>
#include <nui/frontend/attributes/svg/font_size_adjust.hpp>
#include <nui/frontend/attributes/svg/font_stretch.hpp>
#include <nui/frontend/attributes/svg/font_style.hpp>
#include <nui/frontend/attributes/svg/font_variant.hpp>
#include <nui/frontend/attributes/svg/font_weight.hpp>
#include <nui/frontend/attributes/svg/format.hpp>
#include <nui/frontend/attributes/svg/fr.hpp>
#include <nui/frontend/attributes/svg/from.hpp>
#include <nui/frontend/attributes/svg/fx.hpp>
#include <nui/frontend/attributes/svg/fy.hpp>
#include <nui/frontend/attributes/svg/g.hpp>
#include <nui/frontend/attributes/svg/glyph_name.hpp>
#include <nui/frontend/attributes/svg/glyph_orientation_horizontal.hpp>
#include <nui/frontend/attributes/svg/glyph_ref.hpp>
#include <nui/frontend/attributes/svg/gradient_transform.hpp>
#include <nui/frontend/attributes/svg/gradient_units.hpp>
#include <nui/frontend/attributes/svg/hanging.hpp>
#include <nui/frontend/attributes/svg/height.hpp>
#include <nui/frontend/attributes/svg/horiz_adv_x.hpp>
#include <nui/frontend/attributes/svg/horiz_origin_x.hpp>
#include <nui/frontend/attributes/svg/href.hpp>
#include <nui/frontend/attributes/svg/hreflang.hpp>
#include <nui/frontend/attributes/svg/id.hpp>
#include <nui/frontend/attributes/svg/ideographic.hpp>
#include <nui/frontend/attributes/svg/image_rendering.hpp>
#include <nui/frontend/attributes/svg/in.hpp>
#include <nui/frontend/attributes/svg/intercept.hpp>
#include <nui/frontend/attributes/svg/k.hpp>
#include <nui/frontend/attributes/svg/kernel_matrix.hpp>
#include <nui/frontend/attributes/svg/kernel_unit_length.hpp>
#include <nui/frontend/attributes/svg/kerning.hpp>
#include <nui/frontend/attributes/svg/key_points.hpp>
#include <nui/frontend/attributes/svg/key_splines.hpp>
#include <nui/frontend/attributes/svg/key_times.hpp>
#include <nui/frontend/attributes/svg/lang.hpp>
#include <nui/frontend/attributes/svg/length_adjust.hpp>
#include <nui/frontend/attributes/svg/letter_spacing.hpp>
#include <nui/frontend/attributes/svg/ligthing_color.hpp>
#include <nui/frontend/attributes/svg/limiting_cone_angle.hpp>
#include <nui/frontend/attributes/svg/local.hpp>
#include <nui/frontend/attributes/svg/marker_end.hpp>
#include <nui/frontend/attributes/svg/marker_height.hpp>
#include <nui/frontend/attributes/svg/marker_mid.hpp>
#include <nui/frontend/attributes/svg/marker_start.hpp>
#include <nui/frontend/attributes/svg/marker_units.hpp>
#include <nui/frontend/attributes/svg/marker_width.hpp>
#include <nui/frontend/attributes/svg/mask.hpp>
#include <nui/frontend/attributes/svg/mask_content_units.hpp>
#include <nui/frontend/attributes/svg/mask_units.hpp>
#include <nui/frontend/attributes/svg/mathematical.hpp>
#include <nui/frontend/attributes/svg/max.hpp>
#include <nui/frontend/attributes/svg/media.hpp>
#include <nui/frontend/attributes/svg/method.hpp>
#include <nui/frontend/attributes/svg/min.hpp>
#include <nui/frontend/attributes/svg/mode.hpp>
#include <nui/frontend/attributes/svg/name.hpp>
#include <nui/frontend/attributes/svg/num_octaves.hpp>
#include <nui/frontend/attributes/svg/offset.hpp>
#include <nui/frontend/attributes/svg/on_begin.hpp>
#include <nui/frontend/attributes/svg/on_end.hpp>
#include <nui/frontend/attributes/svg/on_repeat.hpp>
#include <nui/frontend/attributes/svg/opacity.hpp>
#include <nui/frontend/attributes/svg/operator.hpp>
#include <nui/frontend/attributes/svg/order.hpp>
#include <nui/frontend/attributes/svg/orient.hpp>
#include <nui/frontend/attributes/svg/orientation.hpp>
#include <nui/frontend/attributes/svg/origin.hpp>
#include <nui/frontend/attributes/svg/overflow.hpp>
#include <nui/frontend/attributes/svg/overline_position.hpp>
#include <nui/frontend/attributes/svg/overline_thickness.hpp>
#include <nui/frontend/attributes/svg/paint_order.hpp>
#include <nui/frontend/attributes/svg/panose.hpp>
#include <nui/frontend/attributes/svg/path.hpp>
#include <nui/frontend/attributes/svg/path_length.hpp>
#include <nui/frontend/attributes/svg/pattern_content_units.hpp>
#include <nui/frontend/attributes/svg/pattern_transform.hpp>
#include <nui/frontend/attributes/svg/pattern_units.hpp>
#include <nui/frontend/attributes/svg/ping.hpp>
#include <nui/frontend/attributes/svg/pointer_events.hpp>
#include <nui/frontend/attributes/svg/points.hpp>
#include <nui/frontend/attributes/svg/points_at_x.hpp>
#include <nui/frontend/attributes/svg/points_at_y.hpp>
#include <nui/frontend/attributes/svg/points_at_z.hpp>
#include <nui/frontend/attributes/svg/preserve_alpha.hpp>
#include <nui/frontend/attributes/svg/preserve_aspect_ratio.hpp>
#include <nui/frontend/attributes/svg/primitive_units.hpp>
#include <nui/frontend/attributes/svg/r.hpp>
#include <nui/frontend/attributes/svg/radius.hpp>
#include <nui/frontend/attributes/svg/referrer_policy.hpp>
#include <nui/frontend/attributes/svg/ref_x.hpp>
#include <nui/frontend/attributes/svg/ref_y.hpp>
#include <nui/frontend/attributes/svg/rel.hpp>
#include <nui/frontend/attributes/svg/rendering_intent.hpp>
#include <nui/frontend/attributes/svg/repeat_count.hpp>
#include <nui/frontend/attributes/svg/repeat_dur.hpp>
#include <nui/frontend/attributes/svg/required_extensions.hpp>
#include <nui/frontend/attributes/svg/required_features.hpp>
#include <nui/frontend/attributes/svg/restart.hpp>
#include <nui/frontend/attributes/svg/result.hpp>
#include <nui/frontend/attributes/svg/rotate.hpp>
#include <nui/frontend/attributes/svg/rx.hpp>
#include <nui/frontend/attributes/svg/ry.hpp>
#include <nui/frontend/attributes/svg/scale.hpp>
#include <nui/frontend/attributes/svg/seed.hpp>
#include <nui/frontend/attributes/svg/shape_rendering.hpp>
#include <nui/frontend/attributes/svg/slope.hpp>
#include <nui/frontend/attributes/svg/spacing.hpp>
#include <nui/frontend/attributes/svg/specular_constant.hpp>
#include <nui/frontend/attributes/svg/specular_exponent.hpp>
#include <nui/frontend/attributes/svg/speed.hpp>
#include <nui/frontend/attributes/svg/spread_method.hpp>
#include <nui/frontend/attributes/svg/start_offset.hpp>
#include <nui/frontend/attributes/svg/std_deviation.hpp>
#include <nui/frontend/attributes/svg/stemh.hpp>
#include <nui/frontend/attributes/svg/stemv.hpp>
#include <nui/frontend/attributes/svg/stitch_tiles.hpp>
#include <nui/frontend/attributes/svg/stop_color.hpp>
#include <nui/frontend/attributes/svg/stop_opacity.hpp>
#include <nui/frontend/attributes/svg/strikethrough_position.hpp>
#include <nui/frontend/attributes/svg/strikethrough_thickness.hpp>
#include <nui/frontend/attributes/svg/string.hpp>
#include <nui/frontend/attributes/svg/stroke.hpp>
#include <nui/frontend/attributes/svg/stroke_dasharray.hpp>
#include <nui/frontend/attributes/svg/stroke_dashoffset.hpp>
#include <nui/frontend/attributes/svg/stroke_linecap.hpp>
#include <nui/frontend/attributes/svg/stroke_linejoin.hpp>
#include <nui/frontend/attributes/svg/stroke_miterlimit.hpp>
#include <nui/frontend/attributes/svg/stroke_opacity.hpp>
#include <nui/frontend/attributes/svg/stroke_width.hpp>
#include <nui/frontend/attributes/svg/style.hpp>
#include <nui/frontend/attributes/svg/surface_scale.hpp>
#include <nui/frontend/attributes/svg/system_language.hpp>
#include <nui/frontend/attributes/svg/tabindex.hpp>
#include <nui/frontend/attributes/svg/table_values.hpp>
#include <nui/frontend/attributes/svg/target.hpp>
#include <nui/frontend/attributes/svg/target_x.hpp>
#include <nui/frontend/attributes/svg/target_y.hpp>
#include <nui/frontend/attributes/svg/text_anchor.hpp>
#include <nui/frontend/attributes/svg/text_decoration.hpp>
#include <nui/frontend/attributes/svg/text_length.hpp>
#include <nui/frontend/attributes/svg/text_rendering.hpp>
#include <nui/frontend/attributes/svg/to.hpp>
#include <nui/frontend/attributes/svg/transform.hpp>
#include <nui/frontend/attributes/svg/transform_origin.hpp>
#include <nui/frontend/attributes/svg/type.hpp>
#include <nui/frontend/attributes/svg/u.hpp>
#include <nui/frontend/attributes/svg/underline_position.hpp>
#include <nui/frontend/attributes/svg/underline_thickness.hpp>
#include <nui/frontend/attributes/svg/unicode.hpp>
#include <nui/frontend/attributes/svg/unicode_bidi.hpp>
#include <nui/frontend/attributes/svg/unicode_range.hpp>
#include <nui/frontend/attributes/svg/units_per_em.hpp>
#include <nui/frontend/attributes/svg/values.hpp>
#include <nui/frontend/attributes/svg/vector_offset.hpp>
#include <nui/frontend/attributes/svg/version.hpp>
#include <nui/frontend/attributes/svg/vert_adv_y.hpp>
#include <nui/frontend/attributes/svg/vert_origin_x.hpp>
#include <nui/frontend/attributes/svg/vert_origin_y.hpp>
#include <nui/frontend/attributes/svg/view_box.hpp>
#include <nui/frontend/attributes/svg/view_target.hpp>
#include <nui/frontend/attributes/svg/visibility.hpp>
#include <nui/frontend/attributes/svg/v_alphabetic.hpp>
#include <nui/frontend/attributes/svg/v_hanging.hpp>
#include <nui/frontend/attributes/svg/v_ideographic.hpp>
#include <nui/frontend/attributes/svg/v_mathemtical.hpp>
#include <nui/frontend/attributes/svg/width.hpp>
#include <nui/frontend/attributes/svg/widths.hpp>
#include <nui/frontend/attributes/svg/word_spacing.hpp>
#include <nui/frontend/attributes/svg/writing_mode.hpp>
#include <nui/frontend/attributes/svg/x.hpp>
#include <nui/frontend/attributes/svg/x_channel_selector.hpp>
#include <nui/frontend/attributes/svg/x_height.hpp>
#include <nui/frontend/attributes/svg/y.hpp>
#include <nui/frontend/attributes/svg/y_channel_selector.hpp>
#include <nui/frontend/attributes/svg/z.hpp>
#include <nui/frontend/attributes/svg/zoom_and_pan.hpp>
