#include <nui/core.hpp>
#include <nui/window.hpp>

// This file is generated by nui.
#include <index.hpp>

int main() {
  using namespace Nui;

  Window window{{.title = "Nui", .debug = true /* may open dev tools */}};
  window.setSize(480, 320, WebViewHint::WEBVIEW_HINT_NONE);
  window.setHtml(index());
  window.run();
}