#pragma once

#include <nui/elements/html_element.hpp>

NUI_DECLARE_HTML_ELEMENT(h1)
NUI_DECLARE_HTML_ELEMENT(h2)
NUI_DECLARE_HTML_ELEMENT(h3)
NUI_DECLARE_HTML_ELEMENT(h4)
NUI_DECLARE_HTML_ELEMENT(h5)
NUI_DECLARE_HTML_ELEMENT(h6)